run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gofmt
    - goimports
    - revive

linters-settings:
  goimports:
    local-prefixes: github.com/yossigruner/SlotBot
